package com.github.vvorks.builder.client.ui;

import java.util.Map;

import com.github.vvorks.builder.client.agent.ClassAgent;
import com.github.vvorks.builder.client.agent.DataTypeAgent;
import com.github.vvorks.builder.client.common.net.JsonRpcClient;
import com.github.vvorks.builder.client.common.ui.UiApplication;
import com.github.vvorks.builder.client.common.ui.UiEditField;
import com.github.vvorks.builder.client.common.ui.UiHorizontalGroup;
import com.github.vvorks.builder.client.common.ui.UiHorizontalScrollBar;
import com.github.vvorks.builder.client.common.ui.UiNodeBuilder;
import com.github.vvorks.builder.client.common.ui.UiPage;
import com.github.vvorks.builder.client.common.ui.UiPickerField;
import com.github.vvorks.builder.client.common.ui.UiText;
import com.github.vvorks.builder.client.common.ui.UiVerticalList;
import com.github.vvorks.builder.client.common.ui.UiVerticalScrollBar;

public class FieldListPage extends UiPage {

	public FieldListPage(String name, UiApplication app, Map<String, String> params) {
		super(name, app);
	}

	protected FieldListPage(FieldListPage source) {
		super(source);
	}

	@Override
	public FieldListPage copy() {
		return new FieldListPage(this);
	}

	@Override
	protected void initialize() {
		UiApplication app = getApplication();
		JsonRpcClient rpc = app.getRpcClient();
		final double NA = UiNodeBuilder.NA;
		UiNodeBuilder b = new UiNodeBuilder(this, "em");
		UiVerticalList list = new UiVerticalList("list");
		//リストヘッダ
		b.enter(new UiHorizontalGroup("header", list));
			b.style(BuilderStyles.FIELD);
			b.locate(1.0, 1.0, 2.0, NA, NA, 2.5);
			b.enter(new UiText("rowid"));
				b.text("id");
				b.style(BuilderStyles.FIELD);
				b.locate( 0.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiText("fieldId"));
				b.text("fieldId");
				b.style(BuilderStyles.FIELD);
				b.locate( 5.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiText("owner"));
				b.text("owner");
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldOwnerCandidate", 20, 40));
				b.locate( 10.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiText("fieldName"));
				b.text("fieldName");
				b.style(BuilderStyles.FIELD);
				b.locate( 20.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiText("type"));
				b.text("type");
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldTypeCandidate", 20, 40));
				b.locate( 30.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiText("width"));
				b.text("width");
				b.style(BuilderStyles.FIELD);
				b.locate( 40.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiText("scale"));
				b.text("scale");
				b.style(BuilderStyles.FIELD);
				b.locate( 45.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiText("cref"));
				b.text("cref");
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldCrefCandidate", 20, 40));
				b.locate( 50.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiText("eref"));
				b.text("eref");
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldErefCandidate", 20, 40));
				b.locate( 60.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiText("fref"));
				b.text("fref");
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldFrefCandidate", 20, 40));
				b.locate( 70.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiText("pk"));
				b.text("pk");
				b.style(BuilderStyles.FIELD);
				b.locate( 80.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiText("nullable"));
				b.text("nullable");
				b.style(BuilderStyles.FIELD);
				b.locate( 85.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiText("needsSum"));
				b.text("sum");
				b.style(BuilderStyles.FIELD);
				b.locate( 90.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiText("needsAvg"));
				b.text("avg");
				b.style(BuilderStyles.FIELD);
				b.locate( 95.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiText("needsMax"));
				b.text("max");
				b.style(BuilderStyles.FIELD);
				b.locate(100.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiText("needsMin"));
				b.text("min");
				b.style(BuilderStyles.FIELD);
				b.locate(105.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiText("title"));
				b.text("title");
				b.style(BuilderStyles.FIELD);
				b.locate(110.0, 0.0, NA, NA, 20.0, 2.0);
			b.leave();
			b.enter(new UiText("description"));
				b.text("description");
				b.style(BuilderStyles.FIELD);
				b.locate(130.0, 0.0, NA, NA, 20.0, 2.0);
			b.leave();
			b.enter(new UiText("note"));
				b.text("note");
				b.style(BuilderStyles.FIELD);
				b.locate(150.0, 0.0, NA, NA, 30.0, 2.0);
			b.leave();
		b.leave();
		//リスト
		b.enter(list);
			b.style(BuilderStyles.FIELD);
			b.source(new BuilderRpcDataSource(rpc, "listField", 20, 40));
			b.locate(1.0, 3.5, 2.0, 2.0, NA, NA);
			b.loop(true);
			b.flushSoon(false);
			//
			b.enter(new UiEditField(UiVerticalList.ROWID_COLUMN));
				b.style(BuilderStyles.FIELD);
				b.locate( 0.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("fieldId"));
				b.style(BuilderStyles.FIELD);
				b.locate( 5.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiPickerField("owner", ClassAgent.get()));
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldOwnerCandidate", 20, 40));
				b.locate( 10.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiEditField("fieldName"));
				b.style(BuilderStyles.FIELD);
				b.locate( 20.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiPickerField("type", DataTypeAgent.get()));
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldTypeCandidate", 20, 40));
				b.locate( 30.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiEditField("width"));
				b.style(BuilderStyles.FIELD);
				b.locate( 40.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("scale"));
				b.style(BuilderStyles.FIELD);
				b.locate( 45.0, 0.0, NA, NA,  5.0, 2.0);
			b.leave();
			b.enter(new UiPickerField("cref", ClassAgent.get()));
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldCrefCandidate", 20, 40));
				b.locate( 50.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiPickerField("eref", ClassAgent.get()));
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldErefCandidate", 20, 40));
				b.locate( 60.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiPickerField("fref", ClassAgent.get()));
				b.style(BuilderStyles.FIELD);
				b.source(new BuilderRpcDataSource(rpc, "listFieldFrefCandidate", 20, 40));
				b.locate( 70.0, 0.0, NA, NA, 10.0, 2.0);
			b.leave();
			b.enter(new UiEditField("pk"));
				b.style(BuilderStyles.FIELD);
				b.locate( 80.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("nullable"));
				b.style(BuilderStyles.FIELD);
				b.locate( 85.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("needsSum"));
				b.style(BuilderStyles.FIELD);
				b.locate( 90.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("needsAvg"));
				b.style(BuilderStyles.FIELD);
				b.locate( 95.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("needsMax"));
				b.style(BuilderStyles.FIELD);
				b.locate(100.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("needsMin"));
				b.style(BuilderStyles.FIELD);
				b.locate(105.0, 0.0, NA, NA, 5.0, 2.0);
			b.leave();
			b.enter(new UiEditField("title"));
				b.style(BuilderStyles.FIELD);
				b.locate(110.0, 0.0, NA, NA, 20.0, 2.0);
			b.leave();
			b.enter(new UiEditField("description"));
				b.style(BuilderStyles.FIELD);
				b.locate(130.0, 0.0, NA, NA, 20.0, 2.0);
			b.leave();
			b.enter(new UiEditField("note"));
				b.style(BuilderStyles.FIELD);
				b.locate(150.0, 0.0, NA, NA, 30.0, 2.0);
			b.leave();
		b.leave();
		b.enter(new UiVerticalScrollBar("vsb"));
			b.related(list);
			b.style(BuilderStyles.SB);
			b.focusable(false);
			b.locate(NA, 3.5, 1.0, 2.0, 1.0, NA);
		b.leave();
		b.enter(new UiHorizontalScrollBar("hsb"));
			b.related(list);
			b.style(BuilderStyles.SB);
			b.focusable(false);
			b.locate(1.0, NA, 2.0, 1.0, NA, 1.0);
		b.leave();
	}

}
